language: node_js
node_js:
  - 0.12
script:
  - npm run lint
  - npm run test
before_script:
  - "npm install fis3 -g"
after_script:
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - master